### ISSUE TITLE
Need something to make debugging a grammar easier

### ISSUE THREAD

**Issue by bkovitz** [mbutterick/brag#19]
Regardless of whether the preceding issue is really a bug, it would help enormously to have something like `yydebug` in _yacc_ or `(debug filename)` in [`br-parser-tools/yacc`](https://docs.racket-lang.org/br-parser-tools/LALR_1__Parsers.html?q=debug). If I could see the possible parses in progress as the parser consumes tokens, that would be plenty. Even just being able to look at the generated parsing table might help.

**Comment by mbutterick** [comment]
`brag` is mostly just a front end to [`cfg-parser`](https://docs.racket-lang.org/br-parser-tools/Context-Free_Parsers.html?q=debug). AFAICT the `debug` option is not part of that parser.

**Comment by mbutterick** [comment]
“The cfg-parser form does not support the precs, suppress, debug, or yacc-output options of parser.”

**Comment by mbutterick** [comment]
Therefore this issue belongs in [`parser-tools`](https://github.com/racket/parser-tools). If it’s fixed there, I can propagate it to `br-parser-tools`.
