### ISSUE TITLE
Docs URL returns 404

### ISSUE THREAD

**Issue by thelonious** [mbutterick/brag#20]
You mentioned that you're in the process of re-arranging things, so this is probably a temporary error, but just wanted to let you know that the README's link to the docs returns a 404:

> http://docs.racket-lang.org/brag/

The Racket Package Index shows the same along with a build failure:

![image](https://user-images.githubusercontent.com/34288/57159078-ec190f80-6d99-11e9-93eb-5bef06365b95.png)

**Comment by mbutterick** [comment]
Thanks, I should be able to fix that in tonight’s build. Of course, the docs are also built locally on your machine.

**Comment by thelonious** [comment]
I may have been looking in the wrong place, but I didn't see a `doc` folder in my `brag` package install. I ended up learning how to build them myself, so it was a good exercise regardless :)

**Comment by mbutterick** [comment]
Hmm, well maybe I messed them both up … 🙄 

I pushed a fix earlier. You can try `raco pkg update brag` and then `raco docs brag` to see if it worked (I just tried it locally, and it was fine)

**Comment by thelonious** [comment]
Running `raco pkg update brag` did the trick. I now have docs in the package folder.
