### ISSUE TITLE
Minor code correction in the Quick Start docs

### ISSUE THREAD

**Issue by thelonious** [mbutterick/brag#21]
I tried using the following code from the Quick Start section in the docs:

```scheme
(define (tokenize s)
  (for/list ([str (regexp-match* #px"\\(\|\\)\|\\w+" s)])
    (match str
      ["("
       (token 'LEFT-PAREN str)]
      [")"
       (token 'RIGHT-PAREN str)]
      [else
       (token 'WORD str)])))
```

Racket complained about the use of `else` in the last clause. I was able to change that to `_` and then it worked fine.

**Comment by mbutterick** [comment]
Strange. What version of Racket? `else` is a little misleading in the context of `match`, but it should work the same way as `_`.

**Comment by thelonious** [comment]
Hmm, seems to be fine now. It must have been a copy/paste error on my part. My apologies.
