### ISSUE TITLE
Support arbitrary unicode codepoint

### ISSUE THREAD

**Issue by locriacyber** [mbutterick/brag#29]
Currently, the following code is invalid.
```
#lang brag
graphic: "\x21".."\x7E" # "!".."~"
utf8: "\u0080".."\uFFFF"
```

What's the behavior of brag when handling unicode strings? [Racket's documentation](https://docs.racket-lang.org/guide/characters.html) says a string is a list of codepoints.

**Comment by mbutterick** [comment]
I can look into it. The `..` character-range operator is part of neither Racket nor brag, however.
