### ISSUE TITLE
cannot parse words "start", "error", "atok"

### ISSUE THREAD

**Issue by rain-1** [mbutterick/brag#3]
```
#lang brag
foo   : "start"
```

.racket/6.12/pkgs/brag/brag/cfg-parser/cfg-parser.rkt:708:55: parser-non-terminals: start used as both token and non-terminal in: start

**Comment by mbutterick** [comment]
I see what you mean. This is a bug in the underlying `ragg` code (which I didn’t write) so it will take me some time to figure it out. In the meantime, you can probably work around by specifying the rule like so?

```racket
#lang brag
foo : "star" "t"
```

**Comment by mbutterick** [comment]
Note to self: check if this is an insurmountable restriction of the underlying `cfg-parser` function. If so, the only “fix” is to amend the docs with a list of reserved words.

**Comment by mbutterick** [comment]
I was able to rehabilitate `"start"` and `"atok"` as literal tokens. But [according to the `br-parser-tools` docs](
https://docs.racket-lang.org/br-parser-tools/Lexers.html?q=cfg-parser#%28form._%28%28lib._br-parser-tools%2Flex..rkt%29._define-tokens%29%29), “A token cannot be named `error`, since `error` it has special use in the parser.” I’ve also updated the `brag` docs to note this.

**Comment by rain-1** [comment]
Thanks for looking into this.

I git cloned the latest and tried cd brag ; raco pkg install but I got a lot of errors. If I cd brag and do raco test . i get some files running then `brag/brag/brag.scrbl:6:21: cannot open module file module path: brag/support` failure.

How should I test this latest commit?

--------------
```
raco setup: error: during making for <pkgs>/brag/brag/brag/test
raco setup:   brag/brag/test/test-parser.rkt:6:9: collection not found
raco setup:     for module path: brag/rules/parser
raco setup:     collection: "brag/rules"

standard-module-name-resolver: collection not found
  for module path: brag/rules/rule-structs
  collection: "brag/rules"
  in collection directories:
   /home/ivy/.racket/6.12/collects
   /usr/share/racket/collects
```

**Comment by mbutterick** [comment]
I’m not sure a direct `git clone` will work, because this repo holds a multi-collection package. Better to use `raco pkg update brag`.

**Comment by mbutterick** [comment]
(BTW I can’t reproduce these errors locally, nor do they show up on Travis, which heightens my suspicion that the `git clone` technique is the problem)

**Comment by rain-1** [comment]
I tried `raco pkg update brag` but it got me the latest release from racket pkgs which seems to be before this latest git commit with the "start" fix.

**Comment by mbutterick** [comment]
You can also do `raco pkg install https://github.com/mbutterick/brag.git?path=brag` if the package server isn’t going fast enough

**Comment by rain-1** [comment]
thanks a lot that worked, I see that I can use "start" now but not "%start".

**Comment by mbutterick** [comment]
OK, fixed that
